# This file was generated by GoReleaser. DO NOT EDIT.
cask "flightcli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d74cef2f0c84f5d9c4462148091e52bd81121d18d468e794834457762f45f07b"
      url "https://github.com/joshuachuah/FlightCLI/releases/download/v#{version}/flightcli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1fc03fdb803fe743bf673040ebe1e8f06d271614b25a6a9b8d5b77ff99ebb56a"
      url "https://github.com/joshuachuah/FlightCLI/releases/download/v#{version}/flightcli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fb8157e85fb65b9530c42914ebc2822b857553fc41863a384556a301222265d2"
      url "https://github.com/joshuachuah/FlightCLI/releases/download/v#{version}/flightcli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "90e1b518dfbdf60c0335188263288a2ac5ec305713a296214c1baf773615ed1c"
      url "https://github.com/joshuachuah/FlightCLI/releases/download/v#{version}/flightcli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flightcli"
  desc "Terminal flight tracker powered by the AviationStack API"
  homepage "https://github.com/joshuachuah/FlightCLI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flightcli"

  # No zap stanza required

end
