# This file was generated by GoReleaser. DO NOT EDIT.
cask "flightcli" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "16e80d7db1bb4fb2880a4ade72a7d09d748173e97c1dff5187027dc1fd246395"
      url "https://github.com/joshuachuah/FlightCLI/releases/download/v#{version}/flightcli_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "46912e4bd1e76f772bc59b63aa85df1e4fa6a7994280419f0c8e41c9b101416f"
      url "https://github.com/joshuachuah/FlightCLI/releases/download/v#{version}/flightcli_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c07aff356d19b303d24c3ab245cb546a0708a0ceab77db4d26ae8ba1a0e2e8f7"
      url "https://github.com/joshuachuah/FlightCLI/releases/download/v#{version}/flightcli_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1ef749a979291ea487de0010ed7be7091518a9f92f5043659d0466d403bdfc5a"
      url "https://github.com/joshuachuah/FlightCLI/releases/download/v#{version}/flightcli_#{version}_linux_arm64.tar.gz"
    end
  end

  name "flightcli"
  desc "Terminal flight tracker powered by the AviationStack API"
  homepage "https://github.com/joshuachuah/FlightCLI"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flightcli"

  # No zap stanza required

end
